<?xml version="1.0" encoding="utf-8"?><Database Name="PERSONELTAKIP" Class="PersonelDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SEMIHPC;Initial Catalog=PERSONELTAKIP;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="PERSONELTAKIPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AYLAR" Member="AYLARs">
    <Type Name="AYLAR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ay" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DEPARTMAN" Member="DEPARTMANs">
    <Type Name="DEPARTMAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmanAd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[IS]" Member="Is">
    <Type Name="I">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Baslik" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Icerik" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsBaslamaTarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsBitisTarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsDurumID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ISDURUM" Member="ISDURUMs">
    <Type Name="ISDURUM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsDurumAd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IZIN" Member="IZINs">
    <Type Name="IZIN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IzinBaslamaTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IzinBitisTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Acıklama" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sure" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IzinDurumID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IZINDURUM" Member="IZINDURUMs">
    <Type Name="IZINDURUM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IzinDurumAd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MAAS" Member="MAAs">
    <Type Name="MAA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Miktar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YIL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ay_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PERSONEL" Member="PERSONELs">
    <Type Name="PERSONEL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Soyad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resim" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PozisyonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Maas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DogumGunu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="isAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.POZISYON" Member="POZISYONs">
    <Type Name="POZISYON">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PozisyonAd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>