//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        public int ID { get; set; }
        public string UrunAd { get; set; }
        public int KategoriID { get; set; }
        public int Stok { get; set; }
        public int Fiyat { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
